### PR TITLE
libpulse & pulseaudio commandline utilities

### PR DESCRIPTION
**Pull request by askorbinovaya-kislota**
should be run with bionic pulseaudio daemon. tested, could listen 1992 year music with `pacat` 😃 

wine depends on pulseaudio for sound, however it is optional (but it works without streaming over tcp, so why not?)

~~also libpulse is a hard dependency for factorio but i didn't test it~~

### CODE REVIEW

**Review by Maxython — CHANGES_REQUESTED** [review]
In the value `TERMUX_PKG_RM_AFTER_INSTALL` from `gpkg/libflac/build.sh`, you forgot to specify the `glibc/` directory (by the way, do these files really need to be deleted?).

In packages where no dependency is specified, you need to set the dependency to `glibc`.

**Comment by Maxython** [comment]
> should be run with bionic pulseaudio daemon. tested, could listen 1992 year music with pacat 😃

Something tells me that all this can be done without using pulseaudio on bionic :/

**Comment by askorbinovaya-kislota** [comment]
> In the value `TERMUX_PKG_RM_AFTER_INSTALL` from `gpkg/libflac/build.sh`, you forgot to specify the `glibc/` directory (by the way, do these files really need to be deleted?).

blindly copied libflac from termux packages, forgot about that useless `TERMUX_PKG_RM_AFTER_INSTALL`

**Comment by eirkkk** [comment]
(libxtst)   I think the problem is that this package is not available.

**Review by Maxython — APPROVED** [review]

**Comment by eirkkk** [comment]
pulseaudio: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

**Comment by eirkkk** [comment]
This option must be activated   --enable-caps

**Comment by Maxython** [comment]
> This option must be activated --enable-caps

For which package?

**Comment by Maxython** [comment]
The PR is ready to be merged with the main branch. The only thing I don't like is that pulseaudio on glibc only works with pulseaudio on bionic. I think that it is possible to make pulseaudio on glibc work independently, so I will investigate this issue.

At the moment I know that pulseaudio on bionic uses [opensl es](https://developer.android.com/ndk/guides/audio/opensl) or [aaudio](https://developer.android.com/ndk/guides/audio/aaudio/aaudio) from the android system. It is extremely difficult to “export” these tools into the glibc environment due to the fact that the only source codes that can be found are only in [Google Open Source](https://android.googlesource.com/), and there the codes are written for the clang (ndk) compiler and also use many functions that are only available in bionic.

**Comment by 500InternalError** [comment]
May I ask how to set up pulseaudio? I always get ```shared memfd open() failed: Invalid argument```

**Comment by Maxython** [comment]
> May I ask how to set up pulseaudio? I always get `shared memfd open() failed: Invalid argument`

First you need to run the following command with pulseaudio on bionic:
```
pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```
Then before running the glibc based command, you must add the following value:
```
export PULSE_SERVER=127.0.0.1
```

**Comment by 500InternalError** [comment]
It works! Thx :)

**Comment by askorbinovaya-kislota** [comment]
> `pacmd load-module module-native-protocol-tcp`

why are you using tcp? socket in `$TMPDIR` worked perfectly for me

i just ran `pulseaudio --exit-idle-time=-1` and every glibc program could use sound without any additional setup

**Pull request merged**
