### PR TITLE
gpkg-dev/glibc: mprotect final fix

### LINKED ISSUE #54: [Bug]: there is something wrong with the last update.
### Problem description

flutter and dart have been working fine. but now flutter not working because dart is having problems with glibc. especially libc.so.6, i don't know. i think this happened aftet i updated with pacman. 

when it was working 
Screenshot_20230717-025132_Termux

now
Screenshot_20230721-163746_Termux
Screenshot_20230721-163804_Termux

### System information

termux-info:
```
```

### LINKED ISSUE #56: [Bug]: box64 crashes on latest glibc with segmentation fault
### Problem description

Box64 fails very fast with segmentation fault on latest glibc. On earlier version of glibc it survives for about 30 secs then fails. I guess it's still related to mprotect(but I'm not sure).
```
~ $ box64 wine winecfg
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Unknown CPU with 8 Cores
Box64 with Dynarec v0.2.3 da098cc1 built on Jul 25 2023 00:16:43
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 32 Env var
Looking for wine
argv[1]="winecfg"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
refreshProtection(0x101801000): 0x101801000/0x7 (ret=0/ok)
Using emulated /data/data/com.termux/files/usr/glibc/bin/../lib/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
refreshProtection(0x10201a000): 0x10201a000/0x7 (ret=0/ok)
refreshProtection(0x10201b000): 0x10201b000/0x7 (ret=0/ok)
refreshProtection(0x102038000): 0x102038000/0x7 (ret=0/ok)
refreshProtection(0x102034000): 0x102034000/0x7 (ret=0/ok)
refreshProtection(0x102035000): 0x102035000/0x7 (ret=0/ok)
refreshProtection(0x102039000): 0x102039000/0x7 (ret=0/ok)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Unknown CPU with 8 Cores
Box64 with Dynarec v0.2.3 da098cc1 built on Jul 25 2023 00:16:43
BOX64: Wine preloader detected, loading "/data/data/com.termux/files/usr/glibc/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 34 Env var
Looking for /data/data/com.termux/files/usr/glibc/bin/wine
argv[1]="winecfg"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
refreshProtection(0x101801000): 0x101801000/0x7 (ret=0/ok)
Using emulated /data/data/com.termux/files/usr/glibc/bin/../lib/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
refreshProtection(0x10201a000): 0x10201a000/0x7 (ret=0/ok)
refreshProtection(0x10201b000): 0x10201b000/0x7 (ret=0/ok)
refreshProtection(0x102038000): 0x102038000/0x7 (ret=0/ok)
refreshProtection(0x102034000): 0x102034000/0x7 (ret=0/ok)
refreshProtection(0x102035000): 0x102035000/0x7 (ret=0/ok)
refreshProtection(0x10206c000): 0x10206c000/0x7 (ret=0/ok)
refreshProtection(0x102067000): 0x102067000/0x7 (ret=0/ok)
refreshProtection(0x102065000): 0x102065000/0x7 (ret=0/ok)
refreshProtection(0x102023000): 0x102023000/0x7 (ret=0/ok)
refreshProtection(0x102020000): 0x102020000/0x7 (ret=0/ok)
refreshProtection(0x10201f000): 0x10201f000/0x7 (ret=0/ok)
refreshProtection(0x10206e000): 0x10206e000/0x7 (ret=0/ok)
refreshProtection(0x102066000): 0x102066000/0x7 (ret=0/ok)
refreshProtection(0x10201e000): 0x10201e000/0x7 (ret=0/ok)
refreshProtection(0x10206b000): 0x10206b000/0x7 (ret=0/ok)
refreshProtection(0x102046000): 0x102046000/0x7 (ret=0/ok)
refreshProtection(0x10206a000): 0x10206a000/0x7 (ret=0/ok)
refreshProtection(0x102068000): 0x102068000/0x7 (ret=0/ok)
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068ef0 triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068ef0 triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068f25 triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068f65 triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068f72 triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068fab triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068fcb triggered a segfault, cancelling
FillBlock triggered a segfault at 0x102069000 from 0x7423991f30
FillBlock at 0x102068fe1 triggered a segfault, cancelling
refreshProtection(0x102069000): 0x102069000/0x7 (ret=0/ok)
32093|SIGSEGV @0x74236ee278 (???(0x74236ee278)) (x64pc=0x102069001//data/data/com.termux/files/usr/glibc/bin/../lib/wine/x86_64-unix/ntdll.so:"/data/data/com.termux/files/usr/glibc/bin/../lib/wine/x86_64-unix/ntdll.so + 0x59001", rsp=0x10200e940, stack=0x101810000:0x102010000 own=(nil) fp=0x1022d0008), for accessing 0x1 (code=1/prot=0), db=0x7423806f90(0x74236ee278:0x74236f6ae8/0x102069001:0x10206a00e//data/data/com.termux/files/usr/glibc/bin/../lib/wine/x86_64-unix/ntdll.so + 0x59001:clean, hash:dc380df5/dc380df5) handler=(nil)
RAX:0x0000000000000001 RCX:0x0000000000000000 RDX:0x00000001022d0000 RBX:0x00000001022d0000
RSP:0x000000010200e940 RBP:0x00000001022d0008 RSI:0x0000000000000000 RDI:0x000000010200ea48
 R8:0x00000000ffffffff  R9:0x0000000000000000 R10:0x0000000000000021 R11:0x0000000000000000
R12:0x0000000000001000 R13:0x000000007ffe0000 R14:0x000000007ffe1000 R15:0x0000000102084650
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053
RSP-0x20:0x000000002dc5d2d0 RSP-0x18:0x0000000064bf32f8 RSP-0x10:0x000000002dc5d2d0 RSP-0x08:0x0000000000000000
RSP+0x00:0x0000000000000000 RSP+0x08:0x0000002100000000 RSP+0x10:0x0000000100000021 RSP+0x18:0x000000010200ea48
Segmentation fault
```
A more detailed log here
[log.txt](https://github.com/termux-pacman/glibc-packages/files/12156613/log.txt)

### System information

termux-info:
```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=31633
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://service.termux-pacman.dev/main/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64
[x11]
Usage = All
Server = https://service.termux-pacman.dev/x11/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://service.termux-pacman.dev/root/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://service.termux-pacman.dev/tur/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://service.termux-pacman.dev/tur-continuous/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
[tur-multilib]
Usage = All
Server = https://service.termux-pacman.dev/tur-multilib/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/tur-multilib/aarch64
[gpkg-dev]
Usage = All
Server = https://service.termux-pacman.dev/gpkg-dev/aarch64
Server = https://s3.amazonaws.com/termux-pacman.us/gpkg-dev/aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 5.10.136-android12-9-722251-abX700ZCU4BWD4 #1 SMP PREEMPT Fri Apr 21 02:30:29 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X700
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=
Installed termux plugins:
com.termux.x11 versionCode:12
```

### PR DESCRIPTION
**Pull request by Maxython**
close #56
close #54

### CODE REVIEW

**Comment by szllzs** [comment]
have a new build?

**Comment by Maxython** [comment]
> have a new build?

Unfortunately, not yet. There are conflicts during compilation due to the `strtol` function. I'm trying to solve it but so far without success.

**Comment by szllzs** [comment]
checking whether CET can be enabled... no
configure: error: aarch64-linux-gnu-gcc doesn't support CET

I compiled glibc in gpkg-dev through docker and reported how to solve this error

image

**Comment by Maxython** [comment]
After a lot of research and trying to ~~fix~~ bypass the limitation from `android selinux` by adding `mmap` to `mprotect`, I realized that this is a bad idea. This kind of correction pushes the logic and optimization in a bad way, so I will return it as it was.

Issue #49 can be considered an exception as this error is not caused by glibc but by the `android selinux` policy, which can be easily bypassed with `mmap`.

Maybe there is a method to fix all this competently, but at the moment I don't know it.

**Pull request closed without merging**
